# Generated by Django 2.2.5 on 2019-09-04 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_auto_20190904_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sith',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{2,}$', 'Name must contain only letters (at least 3, 1st - uppercase)', 'invalid_name')]),
        ),
    ]
